#!/usr/bin/env bash

# Replace (mostly) all snakecase with camelcase (or vice versa if you flip the 
# args of replace-xxx).

./replace-arg0-with-arg1.sh "get_next" "getNext" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "set_next" "setNext" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "set_prev" "setPrev" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "get_prev" "getPrev" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "set_element" "setElement" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "get_element" "getElement" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "get_next" "getNext" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "set_next" "setNext" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "set_prev" "setPrev" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "get_prev" "getPrev" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "set_element" "setElement" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "get_element" "getElement" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "get_next" "getNext" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "set_next" "setNext" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "set_prev" "setPrev" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "get_prev" "getPrev" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "set_element" "setElement" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "get_element" "getElement" "include/singly-linked-list.h"

./replace-arg0-with-arg1.sh "curr_next" "currNext" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "curr_next" "currNext" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "other_curr" "otherCurr" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "other_curr" "otherCurr" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "rhs_curr" "rhsCurr" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "rhs_curr" "rhsCurr" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "curr_next" "currNext" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "curr_next" "currNext" "include/doubly-linked-list.h"
./replace-arg0-with-arg1.sh "other_curr" "otherCurr" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "other_curr" "otherCurr" "include/doubly-linked-list.h"
./replace-arg0-with-arg1.sh "rhs_curr" "rhsCurr" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "rhs_curr" "rhsCurr" "include/doubly-linked-list.h"
./replace-arg0-with-arg1.sh "curr_next" "currNext" "src/hash-map.cpp"
./replace-arg0-with-arg1.sh "curr_next" "currNext" "include/hash-map.h"
./replace-arg0-with-arg1.sh "other_curr" "otherCurr" "src/hash-map.cpp"
./replace-arg0-with-arg1.sh "other_curr" "otherCurr" "include/hash-map.h"
./replace-arg0-with-arg1.sh "rhs_curr" "rhsCurr" "src/hash-map.cpp"
./replace-arg0-with-arg1.sh "rhs_curr" "rhsCurr" "include/hash-map.h"

./replace-arg0-with-arg1.sh "pop_front" "popFront" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "pop_back" "popBack" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "push_front" "pushFront" "src/doubly-linked-list.cpp"
./replace-arg0-with-arg1.sh "pop_front" "popFront" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "pop_back" "popBack" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "push_front" "pushFront" "src/singly-linked-list.cpp"
./replace-arg0-with-arg1.sh "pop_front" "popFront" "include/doubly-linked-list.h"
./replace-arg0-with-arg1.sh "pop_back" "popBack" "include/doubly-linked-list.h"
./replace-arg0-with-arg1.sh "push_front" "pushFront" "include/doubly-linked-list.h"
./replace-arg0-with-arg1.sh "pop_front" "popFront" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "pop_back" "popBack" "include/singly-linked-list.h"
./replace-arg0-with-arg1.sh "push_front" "pushFront" "include/singly-linked-list.h"

./replace-arg0-with-arg1.sh "get_key" "getKey" "include/hash-map.h"
./replace-arg0-with-arg1.sh "get_value" "getValue" "include/hash-map.h"
./replace-arg0-with-arg1.sh "set_key" "setKey" "include/hash-map.h"
./replace-arg0-with-arg1.sh "set_value" "setValue" "include/hash-map.h"
./replace-arg0-with-arg1.sh "get_key" "getKey" "include/hash-map.cpp"
./replace-arg0-with-arg1.sh "get_value" "getValue" "include/hash-map.cpp"
./replace-arg0-with-arg1.sh "set_key" "setKey" "include/hash-map.cpp"
./replace-arg0-with-arg1.sh "set_value" "setValue" "include/hash-map.cpp"
